### PR TITLE
Script to download test data

### PR DESCRIPTION
**Pull request by forsyth2**
Download test data from https://web.lcrc.anl.gov/public/e3sm/e3sm_diags_test_data/ rather than using `scp -r`, as discussed in #368.

### CODE REVIEW

**Review by forsyth2 — COMMENTED** [review]
@chengzhuzhang This pull request will allow the automated tests to download the test data without needing a SSH connection to `Blues`. It does have the disadvantage that all files to be downloaded must be manually listed in the script. (`scp -r` downloaded the complete directories)

However, it looks to me like https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/download_data.py#L55 also doesn't really get around that problem; it lists the necessary files in a text file.

**Comment by forsyth2** [comment]
I'm looking for a way to download all the files from the web server without explicitly listing them. It would be unreasonable to list every image for the full set run (https://portal.nersc.gov/cfs/e3sm/zhang40/tutorials/run_v230_allsets/viewer/).

**Comment by forsyth2** [comment]
@chengzhuzhang This is ready for review. The download script is convoluted -- it goes through the web server finding files to download and subdirectories to go into. This takes about 4 minutes (`scp` took about 2 minutes) but 1) no login to Blues/Anvil is required and 2) there is no need to specifically list which files to download. Running the tests, with this download step, takes about 6 minutes.

**Review by chengzhuzhang — APPROVED** [review]
This looks good!

**Comment by chengzhuzhang** [comment]
@forsyth2 The Travis CI test failed though, it seems like one of the image checks failed?

**Comment by forsyth2** [comment]
@chengzhuzhang That's strange. I just reran the tests twice locally and they pass. I wonder if something is different in the Travis build -- it looks like the polar image is off by more than five pixels. I wonder if we should increase the max number of mismatched pixels?

**Comment by forsyth2** [comment]
@chengzhuzhang Actually, I just noticed the test prints the number of nonzero pixels -- 189! I don't understand how that can be so different from the local run.

**Comment by forsyth2** [comment]
I ran the Travis CI test again and it came back with the same number of mismatched pixels -- 189. https://web.lcrc.anl.gov/public/e3sm/e3sm_diags_test_data/unit_test_images/polar/ERA-Interim/ERA-Interim-T-850-ANN-polar_S.png is the image causing problems.

**Comment by chengzhuzhang** [comment]
It is quite some difference. This is puzzling. I recall that we had faulty polar plots at one time when `cartopy` was updated. But it does seem the Travis CI build gets the good version of `cartopy`. I'm wondering if we can try to `download` the image generated from Travis and to visual check?

**Comment by forsyth2** [comment]
@chengzhuzhang I can't find a simple way of downloading the image generated by Travis CI. (It looks like I would have to set up some sort of deployment?) I did however discover that running on Cori in the `e3sm_unified_1.4.0` environment _also_ causes a mismatch of 189 pixels on that image. The diff of the image produced on Cori and the image produced locally is blank as far as I can tell. Apparently, 189 pixels isn't enough to be visible.

**Comment by forsyth2** [comment]
@chengzhuzhang The images have 2,103,750 pixels. 189 mismatched pixels / 2,103,750 total pixels = 0.00898% mismatch rate. Do you think I should just change the mismatched pixel check to use a percentage rather than a flat number?

**Comment by chengzhuzhang** [comment]
Good idea!

**Comment by forsyth2** [comment]
The check on fraction of mismatched pixels worked.

Going forward, all unit tests should pass on Travis CI before merging code into `master`.

**Comment by forsyth2** [comment]
Confirming that tests on `master` pass: https://travis-ci.org/github/E3SM-Project/e3sm_diags/builds/753451220

**Pull request merged**
