### PR TITLE
save data for plotted variables to fix 448

### PR DESCRIPTION
**Pull request by chengzhuzhang**
This PR is to fix issue #448 reported by @xuezhengllnl 
The meta data for diurnal cycle plot after fixing shown as below. A test run on lat-lon map with `save_netcdf` on was conducted and saved nc files as expected. 
```
netcdf TRMM-3B43v-7_3hr-PRECT-JJA-CONUS_ref {
dimensions:
	lat = 100 ;
	bound = 2 ;
	lon = 240 ;
variables:
	double lat(lat) ;
		lat:bounds = "lat_bnds" ;
		lat:axis = "Y" ;
		lat:units = "degrees_north" ;
		lat:long_name = "Latitude" ;
		lat:standard_name = "latitude" ;
		lat:realtopology = "linear" ;
	double lat_bnds(lat, bound) ;
	double lon(lon) ;
		lon:bounds = "lon_bnds" ;
		lon:axis = "X" ;
		lon:modulo = 360. ;
		lon:topology = "circular" ;
		lon:units = "degrees_east" ;
		lon:long_name = "Longitude" ;
		lon:standard_name = "longitude" ;
		lon:realtopology = "circular" ;
	double lon_bnds(lon, bound) ;
	double PRECT_diurnal_cycmean(lat, lon) ;
		PRECT_diurnal_cycmean:longname = "Mean of diurnal cycle of PRECT" ;
		PRECT_diurnal_cycmean:units = "mm/day" ;
		PRECT_diurnal_cycmean:missing_value = 1.e+20 ;
		PRECT_diurnal_cycmean:_FillValue = 1.e+20 ;
	double PRECT_diurnal_amplitude(lat, lon) ;
		PRECT_diurnal_amplitude:longname = "Amplitude of diurnal cycle of PRECT" ;
		PRECT_diurnal_amplitude:units = "mm/day" ;
		PRECT_diurnal_amplitude:missing_value = 1.e+20 ;
		PRECT_diurnal_amplitude:_FillValue = 1.e+20 ;
	double PRECT_diurnal_phase(lat, lon) ;
		PRECT_diurnal_phase:longname = "Phase of diurnal cycle of PRECT" ;
		PRECT_diurnal_phase:units = "hour" ;
		PRECT_diurnal_phase:missing_value = 1.e+20 ;
		PRECT_diurnal_phase:_FillValue = 1.e+20 ;

// global attributes:
		:Conventions = "CF-1.0" ;
}
```

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey @forsyth2 and @xuezhengllnl , if you could visual check this PR for any problems? Thanks!

A quick test on cori, could be running following command to see if the right files are being created.

`e3sm_diags diurnal_cycle --no_viewer --case_id 'TRMM-3B43v-7_3hr' --save_netcdf --sets 'diurnal_cycle' --run_type 'model_vs_obs' --variables 'PRECT' --seasons 'JJA' --regions 'CONUS' --regrid_tool 'esmf' --regrid_method 'conservative' --main_title 'PRECT Diurnal Cycle JJA CONUS' --backend 'mpl' --output_format 'png' --canvas_size_w '1212' --canvas_size_h '1628' --figsize '8.5' '11.0' --dpi '150' --arrows --test_name '20200517-maint-1.0-tro.A_WCYCL20TRS_CMIP6_HR.ne120_oRRS18v3_ICG.unc11.cam.h5' --short_test_name '0-tro.A_WCYCL20TRS_CMIP6_HR' --test_colormap 'cet_rainbow.rgb' --ref_name 'TRMM-3B43v-7_3hr' --reference_name 'TRMM-3B43v-7' --reference_colormap 'cet_rainbow.rgb' --diff_title 'Model - Observation' --diff_colormap 'diverging_bwr.rgb' --num_workers '4' --granulate 'variables' 'seasons' 'plevs' 'regions' --selectors 'sets' 'seasons' --reference_data_path '/global/cfs/cdirs/e3sm/acme_diags/obs_for_e3sm_diags/climatology' --test_data_path '/global/cfs/cdirs/e3sm/zhang40/tests/rgr/' --results_dir '/global/cfs/cdirs/e3sm/www/zhang40/tests/20200517-maint-1.0-tro.A_WCYCL20TRS_CMIP6_HR.ne120_oRRS18v3_ICG.unc11.cam.h5_dc_notnmlz_save_netcdf'`

**Review by forsyth2 — APPROVED** [review]
Visual check looks good.

I ran your suggested command (with `results_dir` changed) and got the same output for `TRMM-3B43v-7_3hr-PRECT-JJA-CONUS_ref.nc`.

**Review by xuezhengllnl — APPROVED** [review]
It looks good to me. Thanks @chengzhuzhang for fixing this issue. I only visually check the changes. Please let me know if I should run a test for this proposed change.

**Comment by chengzhuzhang** [comment]
Thank you @forsyth2 and @xuezhengllnl !

**Pull request merged**
