### PR TITLE
v2.5.0rc2 update

### PR DESCRIPTION
**Pull request by forsyth2**
Update to `v2.5.0rc2`. #462 will be merged, then this will be merged, then https://github.com/E3SM-Project/e3sm_diags/releases will be updated to include `v2.5.0rc2`.

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey @forsyth2 , please do the `rc2` update after #464. Thank you.

**Comment by forsyth2** [comment]
We may try to address #465 before merging this.

**Comment by xylar** [comment]
> We may try to address #465 before merging this.

Yes, I would really prefer to have that fixed as part of the next RC is possible.  Then, we can start testing if `mpi4py` can be built with system MPI, and if so whether ILAMB works with that build.

**Comment by chengzhuzhang** [comment]
> > We may try to address #465 before merging this.
> 
> Yes, I would really prefer to have that fixed as part of the next RC is possible. Then, we can start testing if `mpi4py` can be built with system MPI, and if so whether ILAMB works with that build.

Hey @xylar, Tom has started on this. Is early next week Okay for next RC? It would be really nice to have e3sm-diags and ilamb to co-exist in one env.

**Comment by xylar** [comment]
Yep, no problem!

**Pull request merged**
