### PR TITLE
Mixed phase partition LCF diagram

### PR DESCRIPTION
**Pull request by chengzhuzhang**
New feature requested by #653 

- [x] Include pre-processing (add CLDLIQ and CLDICE to monthly variable list)
- [x] Add standalone script (TODO add benchmarking data using v1 and v2)
- [x] Add new driver including plotting script, parameter, parser, viewer

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@zyuying and @susburrows I have implemented codes for the T5050 diagram, [here](https://portal.nersc.gov/cfs/e3sm/zhang40/tests/mixed_phase_partition/viewer/) is the link to the example figure. The unresolved part is the variable change for CLDICE from v2 to v3 P3.  I will update this PR as soon as the new variable name/convention is decided on.

**Comment by susburrows** [comment]
This looks great!  It will be great to have this diagnostic available in e3sm_diags so we can easily check on global cloud phase partitioning during model development.

**Comment by chengzhuzhang** [comment]
@zyuying  I was wondering is there an update on the variables to be used for this diagnostics? I'm hoping to have this branch  finalized and merged by the end of this month for a new e3sm_diags release.

**Comment by chengzhuzhang** [comment]
Based on a discussion with @zyuying , this PR can be merged to prepare for joining the e3sm-unified release. There will be a separate PR to add simulator comparison and to accommodate v3 output.

**Pull request merged**
