### PR TITLE
Integrate GitHub Actions CI/CD workflow

### LINKED ISSUE #384: Update CI/CD workflow to single service
The CI/CD build for both CircleCI and TravisCI is currently failing on `master`. This is a blocker for automating docs using CI/CD (#377). 

Problems
---
1. CircleCI [pipelines](https://app.circleci.com/pipelines/github/E3SM-Project/e3sm_diags) outputs the error below:
```
No .circleci/config.yml was found in your project. Add a configuration file to your repository or refer to documentation.
```
Solution: 
We only need one CI/CD service. According to this [comment](https://github.com/E3SM-Project/e3sm_diags/issues/363#issuecomment-739129557), CircleCI was used for testing Mac and TravisCI for Linux. However, separate testing is no longer necessary for Mac.

We should adopt an alternative CI/CD service (CircleCI, GitHub Actions) and purge TravisCI. TravisCI has a new pricing model and is no longer providing CI minutes for open source software.
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> - For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> You will not need to change your build definitions when you are pointed to the new plan
> - When your credit allotment runs out - we'd love for you to consider which of our plans will meet your needs.
> 

2. For TravisCI, the [build log](https://travis-ci.org/github/E3SM-Project/e3sm_diags/builds/756785666) show that it starts failing on PR #375  which includes `test_complete_run.py`. 

**UPDATE: FIXED BY #383** 

I think it was accidentally included in the build’s test runner because there is a comment at the top:.

```
# Due to the large amount of data required to run, this test will be run manually on Anvil
# (rather than as part of the CI tests).
```

From my experience using Pytest, if a test file’s name has a prefix of `test_`, then it will run automatically. 

Solution: Find a way to manually configure the `unittest` test runner to exclude `test_complete_run.py` This is typically done through a config file or as an argument on the command line (e.g. `--exclude test_complete_run.py`).

### PR DESCRIPTION
**Pull request by tomvothecoder**
## Description

This PR replaces the TravisCI and CircleCI services with GitHub Actions. 

Why?
- TravisCI is no longer providing CI minutes to open source/free-tier projects. Once the trial runs out, we are forced to upgrade.
- CircleCI was not configured correctly and originally only used for testing on Mac OS.
- GitHub Actions integration means CI is housed under the GitHub ecosystem, therefore simplifying the software stack. 

Summary of Changes
- Remove TravisCI and CircleCI config files
- Add GitHub Actions CI/CD workflow
  - Runs pre-commit hooks with linters and formatters
  - Builds Conda env and run test suite on Linux and MacOS
  - Publishes to Anaconda when test suite passes on push to master
- Add GitHub Actions badge to README.md
- Run pre-commit hooks on existing files
  - `trailing-whitespace`, `end-of-file-fixer`, `check-yaml` 

Fixes # (issue)
- Closes #384 

## Type of change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by chengzhuzhang — COMMENTED** [review]
Hey Tom, Thanks for the PR. I noticed that  e3sm_diags_env_testing.yml perhaps not very updated. Maybe we can use the dependencies here:https://github.com/E3SM-Project/e3sm_diags/blob/33418de566101dd4580b55cb61609a62ecb5722f/conda/meta.yaml? Also we only need two channels now:
```
channels:
  - conda-forge
  - defaults 
```
As we discussed, in order to pass the test, we need to exclude the test_complete_run ?

**Comment by tomvothecoder** [comment]
> Hey Tom, Thanks for the PR. I noticed that e3sm_diags_env_testing.yml perhaps not very updated. Maybe we can use the dependencies here:https://github.com/E3SM-Project/e3sm_diags/blob/33418de566101dd4580b55cb61609a62ecb5722f/conda/meta.yaml? Also we only need two channels now:
> 
> ```
> channels:
>   - conda-forge
>   - defaults 
> ```
> 
> As we discussed, in order to pass the test, we need to exclude the test_complete_run ?

You're welcome @chengzhuzhang!

Should I copy the `meta.yaml` dependencies and overwrite the ones in `e3sm_diags_env_testing.yml`? I noticed a few dependencies weren't in `meta.yaml`, such as `vcs`, `vtk-cdat`, `vcsaddons`, and `dv3d`. Also I will remove `cdat/label/v82` from the channels as requested.

Yes, we'll need to exclude `test_complete_run.py`. @forsyth2 removed that file in PR #383, so we can wait for it to be merged before merging this one.

**Comment by chengzhuzhang** [comment]
These vcs, vtk-cdat, vcsaddons, and dv3d are no longer dependencies beginning v2.2.0. So copy over meta.yml should be okay. Alternatively, can we just use the development yml? So that we don't need to update two version of .yml files...

**Comment by tomvothecoder** [comment]
@chengzhuzhang sounds good, I'll port the `meta.yml` dependencies. 

We could use `e3sm_diags_env_dev.yml`, but it might increase the CI build time for installing all of the unused dependencies while increasing the conda dependencies cache size. 

If the test environment only requires a small subset of the dependencies, we should either: 
1) Use a separate yml for testing, `e3sm_diags_env_testing.yaml`
  - Pros: Simpler approach, already configured this way
  - Cons: Have to manage separate set of the same dependencies from dev environment which is not best practice
2) Have a `e3sm_diags_env_base.yml`  file for shared base dependencies, and extend those dependencies on a per environment basis such as `e3sm_diags_env_dev.yml` . This will solve the issue of having to manage  same dependencies in different files and allows us to extend dependencies by environment. This approach is typically done with virtualenv and pip `requirements.txt` files (e.g. `base.txt`, `local.txt`, `production.txt`, `testing.txt`).  
  - Pros: Cleaner, separation of concerns by environment, minimize build size/time in CI
  - Cons: More work, not sure how it affects unified environment

I would recommend approach #2 if we want to clean up the dependencies, but I'd have to see if that is even possible with conda yml files.

**Comment by chengzhuzhang** [comment]
Thanks for clarifying, Tom. The meta.yml and development_env.yml contain the same dependencies. The latter has the version of each packages pinned down (we hit instability issues earlier in this project and had to provide, this alternative method turned out to be quite stably). Also, it doesn't look like we can exclude dependencies for testing. I think let's try port over meta.yml to see if it takes too long to build. Also can we test both for Linux and MacOS?

**Comment by tomvothecoder** [comment]
@chengzhuzhang Got it, I'll port the `meta.yml` dependencies to `e3sm_diags_env_testing.yml`. 

GitHub Actions supports testing multiple OS including Linux and MacOS, so I'll add that to the workflow.

**Comment by tomvothecoder** [comment]
@chengzhuzhang, the CI/CD build has a final "release" step that runs `bash nightly_conda_upload.sh`.

This step is included in GitHub Actions, but I noticed a few things about the script:
- It checks for the env variable `TRAVIS_OS_NAME` to set the env var `OS`. `TRAVIS_OS_NAME` is a TravisCI specific env var.
  - Hacky solution: Update GitHub Actions `workflow.yml` to set `TRAVIS_OS_NAME` manually based on `matrix.os` value
  - Clean solution: Update `nightly_conda_upload.sh` to be CI service agnostic and check only `OS` env var is set through CI service
- Env var `CONDA_UPLOAD_TOKEN` is set through TravisCI's settings panel. I need admin access to see what the value is in TravisCI and to be able to set secrets in this repo.

https://github.com/CDAT/cdp/blob/master/conda/nightly_conda_upload.sh

**Comment by tomvothecoder** [comment]
> @chengzhuzhang, the CI/CD build has a final "release" step that runs `bash nightly_conda_upload.sh`.
> 
> This step is included in GitHub Actions, but I noticed a few things about the script:
> 
> * It checks for the env variable `TRAVIS_OS_NAME` to set the env var `OS`. `TRAVIS_OS_NAME` is a TravisCI specific env var.
>   
>   * Hacky solution: Update GitHub Actions `workflow.yml` to set `TRAVIS_OS_NAME` manually based on `matrix.os` value
>   * Clean solution: Update `nightly_conda_upload.sh` to be CI service agnostic and check only `OS` env var is set through CI service
> * Env var `CONDA_UPLOAD_TOKEN` is set through TravisCI's settings panel. I need admin access to see what the value is in TravisCI and to be able to set secrets in this repo.
> 
> https://github.com/CDAT/cdp/blob/master/conda/nightly_conda_upload.sh

To add to this, I looked at the TravisCI logs for this release step and it outputs:

```
after_success
3.56s$ if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then conda install conda-build=2.1.17 && conda install anaconda-client && cd conda && bash nightly_conda_upload.sh; fi
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
PackagesNotFoundError: The following packages are not available from current channels:
  - conda-build=2.1.17
Current channels:
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to
    https://anaconda.org
and use the search bar at the top of the page.
```

It looks like the step has not been working, so I'm not sure if it needs to be fixed or removed from the build.

https://travis-ci.org/github/E3SM-Project/e3sm_diags/jobs/758564024

**Comment by chengzhuzhang** [comment]
Hey, Tom. The `nightly_conda_uploads.py` script generated a while ago was to support nightly conda build (@zshaheen can clarify on this). And as you pointed out, it hasn't been working. I think we can for now remove this script from the build.

**Comment by chengzhuzhang** [comment]
Hey Tom, I'm wondering if we can add release to anaconda's e3sm channel : https://github.com/marketplace/actions/publish-conda-package-to-anaconda-org#publish-anaconda-package
I can add you to admin of e3sm channel for the Annaconda Token.

**Comment by tomvothecoder** [comment]
> Hey Tom, I'm wondering if we can add release to anaconda's e3sm channel : https://github.com/marketplace/actions/publish-conda-package-to-anaconda-org#publish-anaconda-package
> I can add you to admin of e3sm channel for the Annaconda Token.

As suggested, I will drop the reference to the `nightly_conda_uploads.sh` script and instead have the release logic directly in the release step of the CI build. Also, I'll add the required release step dependencies, `conda-build` and `anaconda-client`, to `e3sm_diags_env_testing.yml` so we continue using the latest versions.

**Comment by tomvothecoder** [comment]
@chengzhuzhang Hi Jill, this PR is now ready for final review. The PR description has been updated to reflect the latest state of the branch.

Here's the passing GitHub Actions workflow on my fork: https://github.com/tomvothecoder/e3sm_diags/actions/runs/594313648

**Review by chengzhuzhang — APPROVED** [review]
Very cool! PR looks good.

**Review by forsyth2 — APPROVED** [review]
Looks good, thanks

**Comment by tomvothecoder** [comment]
@chengzhuzhang @forsyth2 Awesome, thanks for reviewing.

**Pull request merged**
