### PR TITLE
Use total (interstitial and cloud-borne) aerosols directly from 2D burdens

### LINKED ISSUE #681: using already column-integrated burdens instead of 3D profiles for aerosol diagnostics
Following up from https://acme-climate.atlassian.net/wiki/spaces/CM/pages/3749576957/2023-04-17+Coupled+Model+-+Meeting+notes. 

Following https://github.com/E3SM-Project/e3sm_diags/pull/676, we should simplify the routine for the burden diags by using already integrated quantities. The details of which are in this comment: https://github.com/E3SM-Project/e3sm_diags/pull/676#issuecomment-1449131478. 

For now, I recommend the following:
- use the `BURDEN` terms if available; or else,
- fail silently or print 0s for the table.

This way, e3sm_diags works as expected and the end user is responsible for ensuring `BURDEN` terms are included in h0 files. In the future we could consider adding these `BURDEN` variables (which are 2D) to the standard output, as opposed to the `Mass_` ones (which are 3D).

Copying  @chengzhuzhang, @golaz, @susburrows, and @kaizhangpnl for awareness. I could submit a PR with the edits in the near future (and with help from Jill, we could finalize this).

### PR DESCRIPTION
**Pull request by mahf708**
Fix #681 

- follow https://github.com/E3SM-Project/E3SM/pull/5774
- instead of doing an offline column integration, we now default to using online calculated burdens

TODO:
- [x] double check for the misc items (deposition, etc.) to ensure they still work (we may need two different dicts to accommodate for different naming conventions)
- [x] test both PRs to v3atm/e3sm and this PR on a production 15-month simulation and post results here

<details><summary>RESULTS</summary>
<p>

The table below shows the calculated burdens based on `Mass_` (current behavior), based on `ABURDEN_` (proposed behavior), and based on `BURDEN_` (by ignoring the cloud-borne portion).

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

merra2.PD | Mass_ | ABURDEN_ | BURDEN_
-- | -- | -- | --
  |   |   |  
Black Carbon |   |   |  
Surface Emission (Tg/yr) | 7.597 | 7.597 | 7.597
Elevated Emission (Tg/yr) | 1.751 | 1.751 | 1.751
Sink (Tg/yr) | 9.379 | 9.379 | 9.379
Dry Deposition (Tg/yr) | 3.566 | 3.566 | 3.566
Wet Deposition (Tg/yr) | 5.813 | 5.813 | 5.813
Burden (Tg) | 0.214 | 0.213 | 0.211
Lifetime (Days) | 8.33 | 8.288 | 8.217
  |   |   |  
Dust |   |   |  
Surface Emission (Tg/yr) | 2848.05 | 2848.05 | 2848.05
Elevated Emission (Tg/yr) | 0 | 0 | 0
Sink (Tg/yr) | 2858.861 | 2858.861 | 2858.861
Dry Deposition (Tg/yr) | 2011.018 | 2011.018 | 2011.018
Wet Deposition (Tg/yr) | 847.843 | 847.843 | 847.843
Burden (Tg) | 24.252 | 24.077 | 23.881
Lifetime (Days) | 3.096 | 3.074 | 3.049
  |   |   |  
Marine Organic Matter |   |   |  
Surface Emission (Tg/yr) | 13.013 | 13.013 | 13.013
Elevated Emission (Tg/yr) | 0 | 0 | 0
Sink (Tg/yr) | 13.114 | 13.114 | 13.114
Dry Deposition (Tg/yr) | 3.238 | 3.238 | 3.238
Wet Deposition (Tg/yr) | 9.875 | 9.875 | 9.875
Burden (Tg) | 0.074 | 0.073 | 0.069
Lifetime (Days) | 2.062 | 2.045 | 1.922
  |   |   |  
Sea Salt |   |   |  
Surface Emission (Tg/yr) | 1956.414 | 1956.414 | 1956.414
Elevated Emission (Tg/yr) | 0 | 0 | 0
Sink (Tg/yr) | 1971.292 | 1971.292 | 1971.292
Dry Deposition (Tg/yr) | 923.677 | 923.677 | 923.677
Wet Deposition (Tg/yr) | 1047.615 | 1047.615 | 1047.615
Burden (Tg) | 5.233 | 5.185 | 4.889
Lifetime (Days) | 0.969 | 0.96 | 0.905
  |   |   |  
Primary Organic Matter |   |   |  
Surface Emission (Tg/yr) | 25.848 | 25.848 | 25.848
Elevated Emission (Tg/yr) | 21.272 | 21.272 | 21.272
Sink (Tg/yr) | 47.103 | 47.103 | 47.103
Dry Deposition (Tg/yr) | 15.941 | 15.941 | 15.941
Wet Deposition (Tg/yr) | 31.162 | 31.162 | 31.162
Burden (Tg) | 1.072 | 1.066 | 1.056
Lifetime (Days) | 8.309 | 8.259 | 8.181
  |   |   |  
Sulfate |   |   |  
Surface Emission (Tg/yr) | 0.987 | 0.987 | 0.987
Elevated Emission (Tg/yr) | 5.499 | 5.499 | 5.499
Sink (Tg/yr) | 93.674 | 93.674 | 93.674
Dry Deposition (Tg/yr) | 21.929 | 21.929 | 21.929
Wet Deposition (Tg/yr) | 71.746 | 71.746 | 71.746
Burden (Tg) | 2.046 | 2.031 | 2.001
Lifetime (Days) | 7.973 | 7.915 | 7.796
  |   |   |  
Secondary Organic Aerosol |   |   |  
Surface Emission (Tg/yr) | 0 | 0 | 0
Elevated Emission (Tg/yr) | 0 | 0 | 0
Sink (Tg/yr) | 117.558 | 117.558 | 117.558
Dry Deposition (Tg/yr) | 21.511 | 21.511 | 21.511
Wet Deposition (Tg/yr) | 96.048 | 96.048 | 96.048
Burden (Tg) | 3.022 | 3.002 | 2.969
Lifetime (Days) | 9.383 | 9.32 | 9.219

</google-sheets-html-origin>

</p>
</details>

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hi @mahf708

This PR itself looks good to me. Just one concern, we may probably roll back to the suggestion you made ([here](https://github.com/E3SM-Project/e3sm_diags/pull/676#issuecomment-1458422051)) to preserve the capability to use MASS_xx based variables for backward compatibility. In that case, for any v2 simulations or their derivatives, where ABURDEN don't exist, we can still use e3sm_diags to analyze burden. It would be the best to differentiate if the variables are derived off-lin or directly output by model (ABURDEN)...

**Comment by susburrows** [comment]
@mahf708 it looks good to me, too.  I think it would make sense to go ahead and get this merged, and then deal with the troposphere/stratosphere burden separation in a separate, follow-up PR.

**Review by susburrows — APPROVED** [review]

**Comment by chengzhuzhang** [comment]
Hey @mahf708 just a gentle reminder that we'd like to include this PR in the new release. Let me know when the PR is ready, i can also test with some files i have which has MASS_xx available. Thank you!

**Review by chengzhuzhang — APPROVED** [review]
Thank you for the PR!

**Comment by chengzhuzhang** [comment]
I was going to test with my copy of file with MASS_ but had permission denied for fetching your folk. Thanks for testing. I will merge now.

**Comment by susburrows** [comment]
Thanks @chengzhuzhang and @mahf708 , glad to see this go in!

**Pull request merged**
