### PR TITLE
global or full longitude map central_lon at 180

### PR DESCRIPTION
**Pull request by chengzhuzhang**
This PR is to fix issue #325 . This issue is caused by central_lon =180 only set with global map, however for the the S60N90 region with full longitude, setting central longitude to180 is also needed. 

CRU-TREFHT-ANN-land_60S90N

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hi @forsyth2 I have tested this PR with lat-lon and RRM config files. Would you please review the codes and also test with relevant configurations? Thank you!

**Comment by forsyth2** [comment]
@chengzhuzhang I checked out this branch, ran `pip install .` and `./tests/test.sh`. All 26 tests passed. They use the configuration at https://github.com/E3SM-Project/e3sm_diags/blob/master/tests/system/all_sets.cfg. Visual inspection of the lat_lon plots looks good to me. Is there another config file I should run/test on?

**Comment by forsyth2** [comment]
@chengzhuzhang I also ran the command from #325 (changing the results dir to my directory) on Cori and the plots look fine to me.

**Comment by chengzhuzhang** [comment]
Thank you for testing, Ryan! I will go ahead and merge.

**Pull request merged**
