### PR TITLE
CDAT Migration Phase 2: Refactor tc_analysis set 

### LINKED ISSUE #668: CDAT Migration Phase 2: Refactor `tc_analysis` set

### PR DESCRIPTION
**Pull request by chengzhuzhang**
## Description

- Closes #668 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@tomvothecoder this PR is ready for review. No .nc or .json files are saved in main, so I performed visual check comparing [main](https://portal.nersc.gov/cfs/e3sm/cdat-migration-fy24/main/viewer/tc_analysis/index.html) vs [development branch](https://portal.nersc.gov/cfs/e3sm/cdat-migration-fy24/688-tc_analysis/viewer/tc_analysis/maps/aew-density-map/plot.html). Results are identical.

**Review by tomvothecoder — APPROVED** [review]
I cleaned up the plotter code (https://github.com/E3SM-Project/e3sm_diags/pull/829/commits/fccb153051a7e4815e069896f9f6987bd4f7dd80) and removed the unused testing notebook (https://github.com/E3SM-Project/e3sm_diags/pull/829/commits/706c09852824b1b6adcd5d56a27bcc8bf254e6a8).

[Results](https://portal.nersc.gov/cfs/e3sm/cdat-migration-fy24/688-tc_analysis-tom/viewer/) are still the same as before. This PR can be merged after the build passes. Thanks for the PR!

**Comment by tomvothecoder** [comment]
The CI/CD build is failing when attempting to download the integration test data from Chrysalis (`HTTP Error 403: Forbidden`).
 
```python
in _call_chain
    result = func(*args)
  File "/usr/share/miniconda3/envs/e3sm_diags_ci/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Downloading integration_test_data
url_prefix=https://web.lcrc.anl.gov/public/e3sm/e3sm_diags_test_data/integration
url_suffix=integration_test_data
(local) directory_prefix=tests/integration/
Downloading files from https://web.lcrc.anl.gov/public/e3sm/e3sm_diags_test_data/integration/integration_test_data; checking for links on tests/integration/integration_test_data.html
Downloading https://web.lcrc.anl.gov/public/e3sm/e3sm_diags_test_data/integration/integration_test_data to tests/integration/integration_test_data.html
```

**Comment by chengzhuzhang** [comment]
@tomvothecoder It looks like an intermittent issue to access the lcrc data server. We can try run again later. Thank you for reviewing and cleaning up this PR!

**Pull request merged**
