### PR TITLE
add TREFMNAV/tasmin TREFMXAV/tasmax to default sets

### LINKED ISSUE #565: Include 'TREFMNAV/tasmin', 'TREFMXAV/tasmax' as standard variables
The monthly average value of the daily minimum and maximum reference height temperatures:'TREFMNAV/tasmin', 'TREFMXAV/tasmax' are now output as standard variables in v2 simulations. Adding both in standard configuration files. tasmin and tasmax from MERRA2 as been processed and included as a reference set.

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Add TREFMNAV/tasmin TREFMXAV/tasmax (the monthly average value of the daily minimum and maximum reference height temperatures) as default variables. Use MERRA2 as reference datasets in model vs obs comparison. 

This PR closes #565

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Interesting to note here about the annual mean maps for TREFHT (upper), TREFMNAV (middle) and TREFMXAV (lower):
Compared to TREFHT, TREFMNAV has a warm signal over southeast Australia, TREFMXAV has a warm signal over northern portion of South America. 

TREFHT: Annual mean of monthly reference height temperatures

Screen Shot 2022-03-03 at 3 48 25 PM
TREFMNAV: Annual mean of the monthly averaged daily minimum

Screen Shot 2022-03-03 at 3 48 43 PM

TREFMXAV: Annual mean of the monthly averaged daily maximum

Screen Shot 2022-03-03 at 3 49 03 PM

Full lat-lon set can be find here: https://compy-dtn.pnl.gov/zhan429/lat_lon_TREFMNAV/v2_6_0_all_sets_compute/viewer/

**Comment by chengzhuzhang** [comment]
Chris suggested to include an additional derived value: mean of daily T range (TREFDiff=TREFMXAV - TREFMNAV), also make diff color scale more linear.

**Comment by chengzhuzhang** [comment]
@golaz Thank you for suggesting additional variable. Adding this derived variable of mean daily temperature range does help to bring out regions with potential bias of daily T change. 
image

**Comment by golaz** [comment]
@chengzhuzhang : very interesting figure, indeed! We have a major problem over in-land seas (Black Sea and Caspian Sea). They may be represented as part of the land model in E3SM.

**Review by golaz — APPROVED** [review]
Based on visual inspection of the figure.

**Comment by chengzhuzhang** [comment]
Thank you, Chris. Yes, I notice that too, both in-land seas are considered as land points in model's land-sea mask, so must be represented by ELM.

**Pull request merged**
