### PR TITLE
Area mean time series refine

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Finalizing are_mean_time_series set:

- Finalizing the logic to compose parameter list for new set with set-specific parameters, enabling model only, model vs obs, model vs models options.
- Refine the driver for the new sets: save metrics, refine plots

A few examples using this branch:
[time_series (model vs obs)](https://compy-dtn.pnl.gov/zhan429/examples/area_mean_with_obs/viewer/) 
[time_series (model vs models)](https://compy-dtn.pnl.gov/zhan429/examples/area_mean_with_models/viewer/area_mean_time_series/index.html)
[all_sets (model vs obs)](https://compy-dtn.pnl.gov/zhan429/examples/all_sets/viewer/)
[latlon and time_series (select same year range)](https://compy-dtn.pnl.gov/zhan429/examples/multiple_sets_2ts/viewer/)

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@golaz Would you please help reviewing this PR? Please also look though the examples and let me know if you'd like any changes. 
To create a development enviroment:
```wget https://raw.githubusercontent.com/E3SM-Project/e3sm_diags/master/conda/e3sm_diags_env_dev.yml```
and do
`conda env create -f e3sm_diags_env_dev.yml`

The configuration python files, are saved under `provenance` folder for testing..

**Comment by golaz** [comment]
@chengzhuzhang : sorry for the delay. 

I was able to reproduce one of your test successfully. I then tried to customize it slightly but ran into a glitch. I wanted to test the option of saving figures in multiple file formats. I added

`param.output_format = ['png', 'pdf', 'svg']`

in `area_mean.py`.

But then I don't get the additional requested output formats. When I print `parameter.output_format` within `area_mean_time_series_plot.py`, it only shows ['png']. So, somehow the modified output_format is not being merged and passed down properly. I don't really know where and how the merge is done, but I can look more into it if needed.

**Comment by chengzhuzhang** [comment]
@golaz Thank you for testing! I didn't try this option out. I will track it down and try fix it.

**Comment by chengzhuzhang** [comment]
@golaz The fix for making following work is in.
```
param.output_format = ['png', 'pdf', 'svg']
```
The issue was that those core-parameters with none-default values were not passed into set-specific parameters. The PR is updated. Thank you for actually testing another parameter. It was really an overlook. Please let me know if it looks okay..

**Comment by chengzhuzhang** [comment]
Hi @zshaheen, When you have time, could you please look at this PR, especially for run.py? I wanted to make sure the changes I made didn't break the logic for compiling the parameter lists.

**Comment by golaz** [comment]
@chengzhuzhang : thanks for fixing the problem. My tests work fine now.

I also pushed a few minor modifications to the branch to be included with this PR:

https://github.com/E3SM-Project/e3sm_diags/commit/61af627d276247f72eeb182532211e0fc22bd7ab : use dpi setting from parameters rather than specifying it in the code.

https://github.com/E3SM-Project/e3sm_diags/commit/4dd7969d3821f5920ae040c7ddf4c07dc2e6572a : option to save subplots as individual files. Note that there is a minor issue with labels on the individual subplots. I don't understand what's causing it, or whether it's a bug in matplotlib. We can live with it for the time being.

**Comment by chengzhuzhang** [comment]
@golaz Thank you for the improvement! It's great.

**Pull request merged**
