### PR TITLE
avoid downloading data

### LINKED ISSUE #900: Discussion about use of https://web.lcrc.anl.gov/ in CI
We have been getting downloads throttled by LCRC on https://web.lcrc.anl.gov/ because we use too much bandwidth.  This is affecting research.

We should seek alternatives to https://web.lcrc.anl.gov/ in our CI, e.g.:
https://github.com/E3SM-Project/e3sm_diags/blob/ca41b0e5d913610c88410928951f1ed11c75663f/tests/integration/download_data.py#L89

### PR DESCRIPTION
**Pull request by mahf708**
## Description

- Closes #900
- See container definition in https://github.com/E3SM-Project/containers/tree/main/e3sm-diags

Instead of downloading the data, run the testing inside a container that has the data. See above for how the container was defined.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

If applicable:

- [x] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by xylar — APPROVED** [review]
Thank you @mahf708, this is a very clean alternative!

**Comment by xylar** [comment]
A questionable use of your Saturday, however :-)

**Review by chengzhuzhang — COMMENTED** [review]
@mahf708 I appreciate the timely solution! Could you provide some guidance on  how to create new images when testing data need to be updated. I suppose the final step is to bump the image version in build_workflow.yml..

**Comment by chengzhuzhang** [comment]
> Most of the process is automated

This is great news! It just occurred to me that the container should be named as `e3sm_diags_testing_data` or some sort. With the name `e3sm_diags` it can be confusing, we had built `e3sm_diags` (the code base) Docker containers a a long time ago...

**Comment by xylar** [comment]
@mahf708, I agree with @chengzhuzhang's suggestion to rename the container.  I initially assumed `e3sm_diags` contained the code itself and not just the test data, which had me concerned.

**Comment by xylar** [comment]
I decided to do my best in: https://github.com/E3SM-Project/containers/pull/22

**Review by xylar — APPROVED** [review]

**Review by tomvothecoder — APPROVED** [review]
This is great! Thank you @mahf708 for the PR and @xylar for reviewing. The data download time is also cut from ~45 sec to  ~1 sec!

**Comment by tomvothecoder** [comment]
I can merge this PR unless there are any other changes. Let me know @mahf708 and @xylar.

**Pull request merged**
