### PR TITLE
Issue213 gpcp

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Fix for https://github.com/E3SM-Project/e3sm_diags/issues/213 for GPCP v2.3 post-processing problem

### CODE REVIEW

**Comment by zshaheen** [comment]
@chengzhuzhang, thanks for doing this. I'll look into this when I get back soon. In the meantime, you will (maybe?) eventually need to regenerate the obs data in a Python 3 env. Please see #215.

**Comment by chengzhuzhang** [comment]
@zshaheen Yes, only a small portion of the scripts are python, so it shouldn't be too bad to convert (to python 3)

**Comment by zshaheen** [comment]
@chengzhuzhang, this looks good. Please merge whenever you want to.

**Comment by zshaheen** [comment]
Please see the [results @chengzhuzhang collected here.](https://github.com/E3SM-Project/e3sm_diags/issues/213#issuecomment-490265545)

**Pull request merged**
