### PR TITLE
postprocessing_E3SM_data_for_e3sm_diags.sh

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Add a post-processing example to prepare E3SM model output to be used in e3sm_diags.

### CODE REVIEW

**Review by czender — COMMENTED** [review]
The script looks fine overall. Two suggestions:
1. `ncclimo` automatically creates output directories so your script can skip this action.
2. Use `$start` and `$end` not the literal years in the `ls` and `ncclimo` calls to that your script only needs to change three lines caseid, start, and end for re-use.

**Comment by chengzhuzhang** [comment]
Thank you @czender. I will remove the `makedir -p` lines. 
I tried a few variation of $start and $end to place in the curly brackets to do pattern matching, but not able to make it work. Not sure how to do it properly in bash...

**Comment by czender** [comment]
It will work with dollarsign variables if you replace `ls` with `eval ls`. Some would say that adding `eval` is a security risk, though.

```
zender@sastrugi:~/data/ne30/raw$ yr_srt='0001'
zender@sastrugi:~/data/ne30/raw$ yr_end='0002'
zender@sastrugi:~/data/ne30/raw$ eval ls *cam.h0.*{${yr_srt}..${yr_end}}*.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-01.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-02.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-02.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-03.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-04.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-05.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-06.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-07.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-08.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-09.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-10.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-11.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-12.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-12.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-01.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-01.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-02.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-03.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-04.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-05.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-06.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-07.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-08.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-09.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-10.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-10.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-11.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-11.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-12.nc
20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0002-12.nc
zender@sastrugi:~/data/ne30/raw$ 

```

**Comment by chengzhuzhang** [comment]
@czender Thank you so much! Adding `eval` works well and is much less lame than the original...Reading on the internet, using `eval` in this case doesn't seem too risky.

**Pull request merged**
