### PR TITLE
Meridional mean 2d

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Adding meridional mean 2d diags set based on user's request.

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Good catch! please see https://portal.nersc.gov/project/acme/zhang40/figs/model_to_obs_meridional_mean/viewer/
Let me know if you spot any problem. Some tweaks in viewer may be needed.

**Comment by zshaheen** [comment]
@chengzhuzhang instead of "meridional_mean_2d" in the image below, what do you want displayed?
Screen Shot 2019-05-16 at 1 01 01 PM


Below is what we are already displaying for the other plot sets.
Screen Shot 2019-05-16 at 1 01 40 PM

**Comment by chengzhuzhang** [comment]
Let's put. "Pressure-Longitude meridional mean contour plot"

**Comment by zshaheen** [comment]
It all looks good. Thanks @chengzhuzhang for doing this.

Screen Shot 2019-05-28 at 1 31 10 PM

Screen Shot 2019-05-28 at 1 31 12 PM

Screen Shot 2019-05-28 at 1 31 18 PM

**Pull request merged**
