### PR TITLE
add_TCO_60S60N to default lat-lon variables

### LINKED ISSUE #878: [Bug]: lat-lon TCO calculations use inconsistent areas
### What happened?

For the lat-lon TCO plots (e.g., https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/E3SMv3/v3.LR.amip_0101/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1985-2014/viewer/lat_lon/omi-mls/tco-global-omi-mls/ann.html), observations are only reliable between 60S-60N, so the min, mean, and max of model TCO should also be calculated for 60S-60N to compare with observations. Currently, the model results are calculated globally, which provides misleadingly too small modeled TCO relative to 60S-60N observations.

The model-obs (bottom) numbers should be updated to only use 60S-60N data too.

### What did you expect to happen? Are there are possible answers you came across?

_No response_

### Minimal Complete Verifiable Example (MVCE)

_No response_

### Relevant log output

_No response_

### Anything else we need to know?

_No response_

### Environment

     active environment : e3sm_unified_1.10.0_login
    active env location : /lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.10.0_login
            shell level : 2
       user config file : /home/ac.qtang/.condarc
 populated config files : /home/ac.qtang/.condarc
          conda version : 24.7.1
    conda-build version : 24.5.1
         python version : 3.8.20.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.7.1=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /lcrc/soft/climate/e3sm-unified/base  (read only)
      conda av data dir : /lcrc/soft/climate/e3sm-unified/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ac.qtang/.conda/pkgs
       envs directories : /home/ac.qtang/.conda/envs
                          /lcrc/soft/climate/e3sm-unified/base/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.8.20 Linux/4.18.0-553.16.1.el8_10.x86_64 rhel/8.10 glibc/2.28 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
                UID:GID : 7976:20001
             netrc file : None
           offline mode : False

### PR DESCRIPTION
**Pull request by chengzhuzhang**
## Description

- Closes #878 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@tangq based on our discussion, I added a new entry to the default lat-lon variable configuration file. This way both `global TCO` and `60S60N TCO` that is consistent to observation record are created. Here is an example run. https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/zhang40/tco/viewer/lat_lon/index.html Notice that all metrics from the diff plots matches except that mean is -2.67 vs -2.68. I suspect the difference was caused by the way how region was subset is slightly different. I'm leaving a note here and later I can check if xarray/xcdat version of e3sm_diags v3 will present the same issue.

**Comment by chengzhuzhang** [comment]
The CI/CD tests are having a bunch of Numpy 2.0 related error: e.g. `https://github.com/E3SM-Project/e3sm_diags/actions/runs/11564567326/job/32189994750`

I think the tests start to pick up numpy 2.0.2. and cdms3.1.5 build 23 (py39h4a6e4dc_23). @xylar there are seem to be remaining issues with numpy 2 compatibility for cdms..

**Comment by xylar** [comment]
@chengzhuzhang, okay, please explicitly constrain to numpy<2.0 for now. Hopefully, the logs will persistent long enough for me to use them for more patching. (What fun!)

**Comment by xylar** [comment]
All errors seem to be the same and form a single line in `cdms2`.  Conda-forge (via Azure) isn't able to build packages right now but I will patch and make a new build as soon as Azure is back up.

**Review by tangq — APPROVED** [review]
@chengzhuzhang , the figures look good. The changes are straightforward - Adding TCO_60S60N as a new variable. I wouldn't worry too much about the small difference in averages (-2.67 vs -2.68).

**Comment by xylar** [comment]
Shoot!  Clearly my local testing didn't catch all the numpy 2.0 issues.  I'll try to figure out why and keep patching.

**Comment by chengzhuzhang** [comment]
@xylar thank you for taking on this task!! And good thing that these CI/CD testing are in place to help inform if the health of the patched builds. ..

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang , the figures look good. The changes are straightforward - Adding TCO_60S60N as a new variable. I wouldn't worry too much about the small difference in averages (-2.67 vs -2.68).

Thank you for reviewing, @tangq !

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang, I'm now able to reproduce the numpy errors locally. I'm re-testing with yet another patched cdms2 ([conda-forge/cdms2-feedstock#97](https://github.com/conda-forge/cdms2-feedstock/pull/97)). I don't want to have to do another cycle so I will keep working locally until tests pass. Sorry for all the noise!

No worries! Hope there aren't too many troubles patching.

**Comment by xylar** [comment]
@chengzhuzhang, we're finally good here, regarding numpy 2.0.  I wouldn't be surprised if more thorough e3sm_diags or other testing reveals some edge cases, though.  Keep me posted.

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang, we're finally good here, regarding numpy 2.0. I wouldn't be surprised if more thorough e3sm_diags or other testing reveals some edge cases, though. Keep me posted.

Awesome! Thank you. Will let you know if more cases are found.

**Pull request merged**
