### PR TITLE
Find bad file descriptor imports

### PR DESCRIPTION
**Pull request by forsyth2**
Find import lines that cause the following error:
```
Fatal error in MPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(572)..............: 
MPID_Init(224).....................: channel initialization failed
MPIDI_CH3_Init(105)................: 
MPID_nem_init(324).................: 
MPID_nem_tcp_init(178).............: 
MPID_nem_tcp_get_business_card(425): 
MPID_nem_tcp_init(384).............: gethostbyname failed, ml-9624328 (errno 1)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=3191567
:
system msg for write_line failure : Bad file descriptor
```
We need to find out why these imports cause the above error on my Mac intermittently;  I don't always get this error.

### CODE REVIEW

**Comment by forsyth2** [comment]
@chengzhuzhang @golaz  It appears the `Bad file descriptor` bug is linked to the imports I've commented out here. I'm not sure why this is so or how to fix the bug (naturally, we can't actually run the code without these imports). Any thoughts?

**Comment by chengzhuzhang** [comment]
@forsyth2 Thank you for tracking down this error. 
https://github.com/E3SM-Project/e3sm_diags/issues/242
https://github.com/E3SM-Project/e3sm_diags/pull/243
See above PRs, which were made to disable mpi to fix the issue that e3sm_diags can't be running in e3sm_unified. It seems like we need to reassess this PR and to find a work-around..

**Comment by zshaheen** [comment]
I remember getting something similar. Running locally on my macOS machine while VPN'ed into LLNL, I would get a similar error, not sure if it's the exact same thing. Everything was fine when not VPN'ed in. You might want to try that and see if that's the issue. This was due to something within CDMS.

Also #212 might be a similar issue.

**Comment by forsyth2** [comment]
@zshaheen Thanks! Yes, disconnecting from VPN does in fact fix the issue. 

@chengzhuzhang We should still investigate why this is the case. It looks like more imports than CDMS caused issues, but maybe CDMS was the root cause?

**Comment by chengzhuzhang** [comment]
Thank you! @zshaheen 
@forsyth2, yeah, do you know what other imports could cause this issue. If it is a CDMS issue, we can fix it..

**Comment by zshaheen** [comment]
@forsyth2, I remember that cdms was the root cause. Even if you comment out all `import cdms2` statements in `e3sm_diags`, you'll probably still get the error since other CDAT packages import cdms.

When investigating this with @doutriaux1 and @dnadeau4 some time (1+ years) ago, it was determined that finding out why this happens and fixing it wasn't worth the time. Most people at the time didn't run `e3sm_diags` on macOS and it was only a problem for the developers who were VPN'ed in.

If you still want to, you'll need to dig into cdms. Good luck.

**Comment by chengzhuzhang** [comment]
@zshaheen Thank you for chiming in! Ryan is also on CDAT team seeking to revamp CDAT with new structure and dependencies, xarray and dask..etc. It's probably not worth to fix in current version of CDAT. But it might be a good learning progress for Ryan to get familiar CDAT and try avoid the similar issues in the long run. Good to hear from you!

**Comment by doutriaux1** [comment]
Might be my memory giving up, especially since I'm no longer on the project but I seem to recall something similar  being due to vpn and macs. Are you under VPN?

**Comment by forsyth2** [comment]
@chengzhuzhang I'm closing this pull request since 1) the commented imports should definitely not be merged and 2) the actual code changes we need would be in CDMS, not in e3sm_diags.

Should I make a GitHub issue in CDMS to at least track this? I didn't see it listed in https://github.com/CDAT/cdms/issues.

**Comment by chengzhuzhang** [comment]
@forsyth2 Can we keep this issue open, so that we can keep track and if other users encounter similar issues they will have a reference? It is a good idea to file a CDMS issue too.

**Comment by forsyth2** [comment]
@chengzhuzhang I created a corresponding issue in CDMS (https://github.com/CDAT/cdms/issues/391) and referenced this pull request. I don't think it makes sense to reopen this pull request though -- I can make a copy of the CDMS issue in this repo, perhaps?

**Comment by chengzhuzhang** [comment]
@forsyth2 oh, I thought this is an issue... Yes, we should have an issue instead of a PR.

**Comment by forsyth2** [comment]
@chengzhuzhang Yeah, I would have made an issue for this but I needed a pull request to show the import lines that caused problems. I just created #287 in this repo to link to the one in CDMS.

**Pull request closed without merging**
