### PR TITLE
integrate in land var pre-processing

### LINKED ISSUE #566: Add model versus model example from ELM runs
Following diags runs provided by @dmricciuto, ex.:https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.ricciuto/GSWP3comp/lat_lon/viewer/

### PR DESCRIPTION
**Pull request by chengzhuzhang**
This PR integrated the preprocessing script @dmricciuto developed for land variables. resolves #566 
The units conversion is now taken care of in derived variable;
and model vs model config is available as default. 
Example output: 
https://portal.nersc.gov/cfs/e3sm/zhang40/tests/lat_lon_test_land_model_vs_model/viewer/

Run script:
```
import os
from e3sm_diags.parameter.lat_lon_land_parameter import LatLonLandParameter # Note the change.
from e3sm_diags.run import runner

param = LatLonLandParameter()
param.test_data_path = '/Users/zhang40/Documents/ACME_simulations/BGC_ELM'
param.test_name = '20220126_CBGCv2.r05.chrysalis.I1850GSWCNP.fnsp' 
#param.short_test_name = 'alpha20_rrm_test'
param.reference_data_path = '/Users/zhang40/Documents/ACME_simulations/BGC_ELM'
param.ref_name = '20220126_CBGCv2.r05.chrysalis.I1850GSWCNP.fnsp' 

param.run_type = 'model_vs_model'
prefix = '/Users/zhang40/Downloads'
param.seasons = ["ANN"]
param.multiprocessing = True
#param.num_workers = 16
param.results_dir = os.path.join(prefix, 'lat_lon_test_land_model_vs_model')
runner.sets_to_run = ['lat_lon_land']   # Note the change
runner.run_diags([param])
```

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@dmricciuto and @jenniferholm, this PR is ready. Let me know if you spot anything suspicious. The only thing I think we could modify is the units of plotted TOT*variables, the values are pretty large. Maybe we can convert to kg instead? But not sure if this makes sense for land modelers...
model vs model (I used the same model to compare with itself) https://portal.nersc.gov/cfs/e3sm/zhang40/tests/lat_lon_test_land_model_vs_model/viewer/

**Comment by jenniferholm** [comment]
Here are some very small requests for changes (they are mostly just cosmetic, and everything looks good!).  In the model to model comparison figures, I see that the top figure has the case title name. Can we also include the case title for the second figure, so that we know which model it goes with? 

Regarding the units for the TOT* variables .... @dmricciuto can you remind us, what are the standard CF units, or the CMIP units used for things like TOTVEGC and the other state variables?  I think it is still g/m2, right?

**Comment by chengzhuzhang** [comment]
Hi Jennifer, I just return to work and get back to this PR. To include the case title for the second plot, the run script can be adjusted by adding:
param.short_ref_name = '20220126_CBGCv2.r05.chrysalis.I1850GSWCNP.fnsp'
or 
param.reference_name = '20220126_CBGCv2.r05.chrysalis.I1850GSWCNP.fnsp'

Above two options controls the title being printed. 
I also added a commit so that when neither of these two are defined, `ref_name` can be printed as case name. 

tagging @dmricciuto for units of those 'TOT*' variables. Otherwise, I think this PR should be ready to merge.

**Comment by jenniferholm** [comment]
@chengzhuzhang - thanks for gettin back to this. Regarding the units of the TOT* outputs, I think we decided that kg/m2 is a better metric and visual than grams/m2. 
Thanks for the information about adding in the case titles. 

In our latest BGC meeting we concluded that there are some additional nutrient outputs that we need to evaluate and diagnosis that are pretty important.  If there is still time, can you please add these outputs to the BGC list? 

New outputs to add are:
FPI
FPI_P
PLANT_NDEMAND
PLANT_PDEMAND
PLANT_CALLOC
PLANT_NALLOC
PLANT_PALLOC
NFIX_TO_SMINN
DENIT
SMIN_NO3_LEACHED

**Comment by chengzhuzhang** [comment]
@jenniferholm sounds good! I will go ahead and do the units conversion for `TOT*`
No problem adding additional variables to the standard list. I'm not familiar with these variables, I'm wondering if @dmricciuto could add those in his pre-processing script, so that I can use the units conversion and contour level choices that would make sense.

**Comment by dmricciuto** [comment]
@chengzhuzhang I am updating the pre-processing script to include these new variables and some additional unit conversions and will pass this on to you soon.

**Comment by chengzhuzhang** [comment]
@jenniferholm and @dmricciuto I will merge this PR for some integration test to get e3sm_diags ready for the up-coming e3sm_unified release. Once I have your input, we can future refine the variables in a new PR.

**Pull request merged**
