### PR TITLE
Optimize nco invocation

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Following best practice of nco invocation.

### CODE REVIEW

**Review by czender — APPROVED** [review]
Looks good. As a reminder, this will work on EAM files with "eam" in the filename. It will break on EAM files with "cam" in the filename. To get the latter to work, you would need to specify `-P eam -m cam`.

**Comment by chengzhuzhang** [comment]
Hey Charlie, thank you for reviewing. I'm a little confused about the note, from EAM files with 'cam' in the filename (e.g. most v1 data), would `-P cam` work? Could explain again the difference between `-P eam -m cam` and `-P cam`. Thanks!

**Comment by czender** [comment]
Yes, if the filenames have "cam" in the name then `-P cam` will work, as will `-P eam -m cam`. I guess my point was that `-P eam` alone will not work on such files.

**Comment by chengzhuzhang** [comment]
It's good to know. Thank you, Charlie.

**Pull request merged**
