### PR TITLE
Add aerosol global metrics benchmarks file

### PR DESCRIPTION
**Pull request by chengzhuzhang**
The Aerosol global metrics benchmarks are compiled by Susannah Burrows (PNNL) @susburrows , with additional feedback provided by Mingxuan Wu , Hailong Wang, Manish Shrivastava, Kai Zhang , Yan Feng, and Naser Mahfouz. More details can be found at https://docs.google.com/spreadsheets/d/1dxallyeq1iudK4cT9kVL0oyTIQIllSgoyn4sBgQUn6E/edit#gid=0. The benchmarks will be used in the aerosol budget tables in model vs obs runs.

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey @susburrows this PR adds the aerosol benchmarks to the budget table. An example output can be viewed here: 
https://compy-dtn.pnl.gov/zhang429/aerosol_budget/viewer/table/20210528.v2rc3e.piControl.ne30pg2_EC30to60E2r2.chrysalis-ANN-budget-table.html

Let me know if you'd like any changes. Thank you for this contribution. It helps a lot for non- aerosol experts like me to get some sense of these budget numbers when comparing.

**Comment by chengzhuzhang** [comment]
@mahf708 Hey Naser, I know that you are working on the same set. Tagging you, so that you are aware changes in this PR and feel free to review or comment.

**Comment by susburrows** [comment]
@chengzhuzhang thanks for doing this so quickly!  I hope this will be a very useful addition for the team.

One minor comment - I am not sure we need so many digits to be printed in some of the terms.  I would recommend printing no more than four significant digits in each metric.  For example:

Surface Emission (Tg/yr) | 2536.00 | 4980 (2030 - 5e4)

can be simplified to:

Surface Emission (Tg/yr) | 2536 | 4980 (2030 - 5e4)

That would also help the table look a bit cleaner / less crowded.

**Comment by chengzhuzhang** [comment]
Thank you for the review @susburrows and @mahf708 
Great idea to limit the digits to print out. I now limited those to four significant digits except Burden and Lifetime are now 3 significant digits. Updated table is [here](https://compy-dtn.pnl.gov/zhang429/aerosol_budget/viewer/table/20210528.v2rc3e.piControl.ne30pg2_EC30to60E2r2.chrysalis-ANN-budget-table.html)

I'm not sure about separating the median and the range into separate columns. Some terms only has median and some only has the range. To have both in one cell might be easier to read. It definitely is possible to change, but I would suggest to keep the form as is.

**Comment by chengzhuzhang** [comment]
I'm merging this PR now. I'm happy to reiterate if any changes and improvements are needed.

**Pull request merged**
