### PR TITLE
CDAT Migration Phase 2: Refactor arm_diags set

### LINKED ISSUE #667: CDAT Migration Phase 2: Refactor `arm_diags` set

### PR DESCRIPTION
**Pull request by chengzhuzhang**
## Description

- Closes #667 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by tomvothecoder** [comment]
This branch needs to be rebased on the latest `cdat-migration-fy24` branch.

**Comment by chengzhuzhang** [comment]
> This branch needs to be rebased on the latest `cdat-migration-fy24` branch.

I was not aware this branch had a force-push. I plan to start from fresh with a new PR.

**Comment by tomvothecoder** [comment]
> > This branch needs to be rebased on the latest `cdat-migration-fy24` branch.
> 
> I was not aware this branch had a force-push. I plan to start from fresh with a new PR.

I re-based `cdat-migration-fy24` on top of `main` with the latest integration test fix from #835. It is a bit of a hassle to do this because it requires the dev branches stemming from `cdat-migration-fy24` to also be re-based. We only have a few sets to deal with this if it happens though.

**Comment by chengzhuzhang** [comment]
Closed in favor of #842

**Pull request closed without merging**
