### PR TITLE
Recipe for v2

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Update recipe with cdat82

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hi, @forsyth2 would you please test the development env to see if this works for you? https://raw.githubusercontent.com/E3SM-Project/e3sm_diags/recipe_for_v2/conda/e3sm_diags_env_dev.yml

**Comment by chengzhuzhang** [comment]
@xylar This [yaml file](https://github.com/E3SM-Project/e3sm_diags/blob/recipe_for_v2/conda/meta.yaml) gives our main dependencies.

**Comment by xylar** [comment]
@chengzhuzhang do you plan to build an osx release, too?  I hope so, because I'm planning to make osx versions of e3sm-unified.

**Comment by chengzhuzhang** [comment]
@xylar Thank you for testing! Glad it works. I'm building with noarch, so no separate build for osx release is needed I suppose.

**Comment by xylar** [comment]
Ah, true!

**Pull request merged**
